post/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r"^post/list", views.PostList.as_view(), name='post-list'),
    url(r"^post/add", views.PostCreate.as_view(), name='post-create'),
    url(r"^(?P<pk>[0-9]+)/$", views.PostDetail.as_view(), name='post-detail'),
    url(r'^post/(?P<pk>[0-9]+)/delete/$', views.PostDelete.as_view(), name='post-delete'),
    # url(r'^post/(?P<pk>[0-9]+)/comment/$', views.CommentUpdate.as_view(), name='comment-create'),
    url(r'^post/(?P<pk>[0-9]+)/comment/$', views.commentcreate, name='comment-create'),
    url(r'^post/count/$', views.like_count, name='like-count'),
    url(r'^post/(?P<pk>[0-9]+)/likecount/$', views.like_count, name='like-count'),
    url(r'^post/(?P<pk>[0-9]+)/dislikecount/$', views.dislike_count, name='dislike-count'),
    ]

social_app/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.views.generic.base import TemplateView
from django.conf import settings
from django.conf.urls.static import static
# from users.views import login_view, logout_view
# from social_app.users import views

urlpatterns = [
    # url(r'^$', core_views.home, name='home'),
    url(r'^login/$', auth_views.login, {'template_name': 'users/login.html'}, name='login'),
    # url(r'^signup/$', signup.as_view, name='signup'),
    url(r'^logout/$', auth_views.logout, {'template_name': 'users/logout.html'}, name='logout'),
    url(r'^oauth/', include('social_django.urls', namespace='social')),  # <--
    url(r'^admin/', admin.site.urls),
    url(r'', include('users.urls')),
    url(r'', include('post.urls')),
    url(r'', include('friendlist.urls')),
]+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT);

post/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
from django.shortcuts import reverse
from users.models import Profile
from datetime import datetime
from django.contrib.auth.models import User

class Post(models.Model):
	user = models.ForeignKey(Profile,null=True)
	title = models.CharField(max_length = 100)
	description = models.CharField(null = True,max_length=100)
	image = models.FileField(upload_to='documents/',null=True)
	
	def __str__(self):
		return str(self.title)
	def get_absolute_url(self):
		return reverse('post-list')
		
class Comment(models.Model):
	user = models.ForeignKey(User)
	post = models.ForeignKey(Post)
	comment = models.CharField(null=False,max_length=200)
	created_at = models.DateTimeField(default=datetime.now, blank=True,null=True)

	def get_success_url(self):
		return reverse_lazy('post-list')
	def get_absolute_url(self):
		return reverse('post-list')

class Like(models.Model):
    user = models.ForeignKey(Profile)
    post = models.ForeignKey(Post)
    created = models.DateTimeField(auto_now_add=True)

post/forms.py
from django import forms
from models import Post,Comment

class PostForm(forms.ModelForm):
	description = forms.CharField(required=True)
	title = forms.CharField(required=True)
	image = forms.FileField(required=True)

	class Meta:
		model = Post
		exclude = ['thumbnail']
		fields=('title','description','image','user')

class CommentForm(forms.ModelForm):
    
    comment = forms.CharField(required=True,)
    class Meta:
        model = Comment	
        fields = ('comment','post','user')


# class CommentForm(forms.Form):
#     comment = forms.CharField(
#         max_length=2000,
#         widget=forms.Textarea(),
#         help_text='Write here your message!'
#     )

post/views.py
from __future__ import unicode_literals
from django.shortcuts import render_to_response
from django.shortcuts import render
from .models import Post,Comment,Like
from django.shortcuts import render
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.http import HttpResponseRedirect,HttpResponse
from django.views.generic import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .forms import CommentForm
from post.models import Profile

class PostList(LoginRequiredMixin,ListView):
    template_name = 'post/list.html'
    model = Post
    paginate_by = 3


class PostCreate(LoginRequiredMixin,CreateView):
    template_name = 'post/create.html'
    model = Post
    fields = ('title','description','image','user')
    def form_valid(self,form):
        save_image = Post(image=self.get_form_kwargs().get('files')['image'])
        save_image.save()
        self.id = save_image.id
        return HttpResponseRedirect("/") 

class PostDetail(UpdateView):
	template_name = 'post/detail.html'
	model = Post


class PostDelete(LoginRequiredMixin, DeleteView):
    model = Post

    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)

    def get_success_url(self):
        return reverse_lazy('post-list')



def commentcreate(request,pk):
    records = Comment.objects.all()
    post_data = Post.objects.filter(id=pk)
    comment_data = Comment.objects.filter(post__id=pk).values('comment')

    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            task = form.save(commit=False)
            task.save()
            return render(request,'post/list.html')
        else:
            return render(request, 'post/partial_comment.html',{'form': form , 'post_data':post_data,'comment_data':comment_data,},)
    else:       
        form = CommentForm()
        return render(request, 'post/partial_comment.html', {'form' : form ,'post_data':post_data,'comment_data':comment_data,})


def like_count(request,pk):
    current_user = request.user
    social_user = request.user.social_auth.filter(
    provider='facebook',).first()

    if request.user.is_authenticated():
        # import pdb
        # pdb.set_trace()
        like_data = Like.objects.filter(user_id=current_user.id,post__id=pk)
        if not like_data :
            like_data = Like.objects.create(user_id=current_user.id,post_id=pk).save()
        else:
            count = like_data.count()
            print count
        return HttpResponseRedirect("/post/list")

def dislike_count(request,pk):
    current_user = request.user
    like_data = Like.objects.filter(user_id=current_user.id,post__id=pk)
    if not like_data :
        pass
    else:
        count = like_data.count()
        print count-1
        return HttpResponseRedirect("/post/list")

templates/post/create.html
{% include 'home.html' %}
{% load i18n %}
{% block content%}
{# Content header #}
{% block header-title %}{% trans 'New Post' %}{% endblock %}

<!-- {% block form-fields-col-width %}
<div class="col-md-12">
{% endblock %} -->
<div class="main">

<form method="POST", action="" , enctype="multipart/form-data">
	{% csrf_token%}
  {{form.as_P}}
	<table class="table table-bordered">
                  <tr>
                    <th>{% trans 'Title' %}</th>
                    <th>{% trans 'Description' %}</th>
                    <th>{% trans 'Image' %}</th> 
                 </tr>
	{% for field in form %}

	 <td> {{field}}</td>
	

{% endfor %}
	 
</table>
<div class="box-header with-border">
        <div class="pull-right">
        <input type="submit" name="status" class="btn btn-primary btn-lg" value="{% trans 'Save' %}">
       <button class=""><a href="/post/list" class="btn btn-lg  btn-default">{% trans 'Cancel' %}</a></button>
        </div>
      </div> </button>
</form>
</div>
</div>
{% endblock %}

templates/post/list.html
{% include 'home.html'%}
{% load i18n %}
{% block content %}
<div class="main">
  <h2>New Post</h2>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<div class="box-body" align="center">
<table>


	{% for post in object_list %}
		
		{{post.profile.user}}
    {{post.description}}
		<img src="{{ post.image.url }}" alt="...">
		

            <a role="button" href="{% url 'post-delete' post.id %}"
               class="btn btn-danger btn-delete"
               data-confirm="{% trans 'Are you sure to delete this item?' %}"><i
                    class=""></i>X</a>{{ post.image }} <br/>
                    
                
        <a href="{% url 'comment-create' post.id%}">See more</a>
            <a href="{% url 'like-count' post.id%}">
  <span class="glyphicon glyphicon-thumbs-up"></span></a>
<a href="{% url 'dislike-count' post.id%}">
          <span class="glyphicon glyphicon-thumbs-down"></span>
        </a>
                    

    
<div >

</div>
{% endfor %}
{% endblock %}
</table>
</div>
</div>

templates/post/partial_comment.html
{% include 'home.html' %}

{% load i18n %}
{% block content%}
<div class="main">
<div align="center">

{% for item in  post_data %}
    
    {{item.image}} 
    <img src="{{ item.image.url }}" alt="...">
  {% endfor %}<br/>

  Comments are:<br/>
  {% for item in  comment_data %}
  {{item.user}}
  {{item.comment}}
  {{item.id}}<br/>
  {% endfor %}
</div>

<form method="POST", action="" , enctype="multipart/form-data">
	{% csrf_token%}
	<table class="table ">

                  
          <label for="user">{% trans '' %}</label>
              <input type="hidden" class="form-control" id="user" name="user" value="{{user.id}}" required>
              <label for="post">{% trans 'post' %}</label>
              <input type="text" class="form-control" id="post" name="post" value="{{postid}}" required>
              <label for="comment">{% trans 'Comment' %}</label>
              {{form.comment}}


	 
</table>

<div class="box-header with-border">
        <div class="pull-right">
        <input type="submit" name="status" class="btn btn-primary btn-lg" value="{% trans 'Save' %}">
        <button><a href="/post/list" class="btn btn-lg  btn-default">{% trans 'Cancel' %}</a></button>
       
        </div>
      </div> </button>
</form>
</div>
</div>
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<script type="text/javascript">
 var a =0
 $("select").chanege(function(){
  a =  $("#id_post").val()
});
</script>
{% endblock %}